### ISSUE TITLE
Error: Cannot find module './parseRoutes'

### ISSUE THREAD

**Issue by raine** [foss-haas/http-proxy-cli#3]
```
~ % npm install -g http-proxy-cli
~ % http-proxy --help
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module './parseRoutes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by wgrabowski** [comment]
Looks like "files" section in package.json should also contains "src" directory
